### ISSUE TITLE
Add kodi, Elisa music player, obs-studio ?

### ISSUE THREAD

**Issue by DraGiuS** [NorcuxOS/build-scripts-rolling#2]
That's what i suggest. 
What do you think ?

**Comment by NorcuxOS** [comment]
Thanks for your suggestion.
Elisa and Kodi (maybe also OBS Studio) will most likely be added.
We will definetely change some programs that will be included by default
and we try too keep the ISO size small.

**Comment by NorcuxOS** [comment]
Hello again. I recently looked at the size and dependencies of Kodi. I think we won't include it because it is a rather big program, but Elisa will be included. In the future you will be able to install it and other programs easily with our Software Center.
